# permissions for end users to edit apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: app-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yueyuea
    app.kubernetes.io/part-of: yueyuea
    app.kubernetes.io/managed-by: kustomize
  name: app-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - apps/status
  verbs:
  - get
- apiGroups: 
  - apps
  resources: 
  - deployments
  verbs: 
  - list
  - get
  - watch
