apiVersion: batch.tutorial.kubebuilder.io/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: yueyuea
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: yueyuea
  name: app-sample
  namespace: default
spec:
  replicas: 3
  podTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nginx-sample
            image: nginx:1.14.2
            ports:
            - containerPort: 80
  